# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-29 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(help_text='<a href="password/">修改密码</a>', max_length=128, verbose_name='password'),
        ),
    ]
